# Generated by Django 4.1.7 on 2023-03-22 16:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=3)),
                ('expdate', models.DateField(default=datetime.datetime.now)),
                ('discount_rate', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('age_rating', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('trailer_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CinManager.film')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CinManager.screen')),
            ],
        ),
        migrations.CreateModel(
            name='ClubRep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateofbirth', models.DateField(default=datetime.datetime.now)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CinManager.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
