# Generated by Django 4.1.7 on 2023-04-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='club',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='club',
            name='expdate',
        ),
    ]
