# Generated by Django 4.1.7 on 2023-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinManager', '0002_remove_club_account_number_remove_club_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imageurl',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
