# Generated by Django 4.1.7 on 2023-04-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinManager', '0003_film_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imageurl',
            field=models.CharField(max_length=1000),
        ),
    ]
