# Generated by Django 4.1.7 on 2023-04-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinManager', '0004_alter_film_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='discount_rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
