# Generated by Django 4.1.7 on 2023-04-16 15:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CinManager', '0003_film_imageurl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cvv', models.CharField(max_length=3)),
                ('expdate', models.DateField(default=datetime.datetime.now)),
                ('balance', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CinManager.club')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('adult_tickets', models.PositiveIntegerField(default=0)),
                ('student_tickets', models.PositiveIntegerField(default=0)),
                ('child_tickets', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.account')),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CinManager.showing')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('adult_tickets', models.PositiveIntegerField(default=0)),
                ('student_tickets', models.PositiveIntegerField(default=0)),
                ('child_tickets', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CinManager.showing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('account_number', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=3)),
                ('expdate', models.DateField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
