# Generated by Django 4.1.7 on 2023-04-16 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='expdate',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{2}/\\d{2}$', 'Expiration date must be in the format MM/YY')]),
        ),
    ]
