# Generated by Django 4.1.7 on 2023-04-16 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_paymentdetails_expdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='expdate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
