# Generated by Django 4.1.7 on 2023-04-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_paymentdetails_expdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='account_number',
            field=models.CharField(max_length=16),
        ),
    ]
