# Generated by Django 4.1.7 on 2023-05-03 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_remove_account_cvv_remove_account_expdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.account')),
            ],
        ),
    ]
