# Generated by Django 4.1.7 on 2023-05-03 20:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_clubreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('startdate', models.DateField(default=datetime.datetime.now)),
                ('enddate', models.DateField(default=datetime.datetime.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.account')),
            ],
        ),
    ]
