# Generated by Django 4.1.5 on 2023-01-13 21:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('discount_rate', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('age_rating', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('trailer_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UWEFlix.film')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UWEFlix.screen')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentCard', models.CharField(max_length=100)),
                ('paymentCardExp', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClubRep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateofbirth', models.DateField(default=datetime.datetime.now)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UWEFlix.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='payment_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlix.paymentdetails'),
        ),
    ]
