# Generated by Django 4.1.5 on 2023-01-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='payment_details',
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
