# Generated by Django 4.1.5 on 2023-01-13 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0002_remove_club_payment_details_delete_paymentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubrep',
            name='dateofbirth',
        ),
    ]
