# Generated by Django 4.1.5 on 2023-01-13 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0003_remove_clubrep_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrep',
            name='dateofbirth',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
