# Generated by Django 4.1.5 on 2023-01-14 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0005_alter_club_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='cvv',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='expdate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
