# Generated by Django 4.1.7 on 2023-03-31 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CinManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Showing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CinManager.showing')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Showing', models.CharField(max_length=100)),
                ('Type', models.PositiveSmallIntegerField()),
                ('Price', models.PositiveIntegerField()),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Bookings.booking')),
            ],
        ),
    ]
