# Generated by Django 4.1.7 on 2023-04-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Showing',
        ),
    ]
