# Generated by Django 4.1.7 on 2023-04-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_remove_ticket_showing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Type',
            field=models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('student', 'Student')], max_length=7),
        ),
    ]
