# Generated by Django 4.1.7 on 2023-04-07 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CinManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bookings', '0004_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Showing',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Booking',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Type',
        ),
        migrations.AddField(
            model_name='booking',
            name='tickets',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Bookings.ticket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Student', 'Student'), ('Child', 'Child')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='booking',
            name='showing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CinManager.showing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
