# Generated by Django 4.1.7 on 2023-04-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0006_alter_ticket_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tickets',
        ),
        migrations.AddField(
            model_name='booking',
            name='adult_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='child_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='student_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
